config/routes.rb
Rails.application.routes.draw do
  get 'blog/new'
  #get 'blog/create'
  get 'blog/edit'
  #get 'blog/update'
  get 'blog/destroy'
  root 'pages#home'
  get '/help', to: 'pages#help'
  get '/contact', to: 'pages#contact'
  get '/home', to: 'pages#home'
  get '/staff', to: 'pages#staff'
  get '/feedback', to: 'pages#feedback'
  get '/modlog', to: 'pages#modlog'
  get '/mystuff', to: 'pages#mystuff'
  get '/my%20stuff', to: 'pages#mystuff'

  get '/plc', to: 'plc#index'
  get '/plc/subject', to: 'plc#subject_slots'

  delete '/logout', to: 'sessions#destroy'
  get '/filter/get', to: 'filters#get', as: 'get_filter'
  post '/filter/update', to: 'filters#update', as: 'update_filter'
  #google
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  post '/event/approve', to: 'events#approve', as: 'approve_event'
  post '/event/reject', to: 'events#reject', as: 'reject_event'
  post '/event/finalize', to: 'events#finalize', as: 'finalize_event'
  get '/event/get_partial', to: 'events#get_partial', as: 'event_get_partial'
  post '/event/rsvp', to: 'events#rsvp', as: 'rsvp_event'
  post '/event/unrsvp', to: 'events#unrsvp', as: 'unrsvp_event'

  post '/announcement/approve', to: 'announcements#approve', as: 'approve_announcement'
  post '/announcement/reject', to: 'announcements#reject', as: 'reject_announcement'
  post '/announcement/finalize', to: 'announcements#finalize', as: 'finalize_announcement'
  get '/announcement/get_partial', to: 'announcements#get_partial', as: 'announcement_get_partial'

  post '/club/approve', to: 'clubs#approve', as: 'approve_club'
  post '/club/reject', to: 'clubs#reject', as: 'reject_club'
  post '/club/finalize', to: 'clubs#finalize', as: 'finalize_club'
  get '/club/get_partial', to: 'clubs#get_partial', as: 'club_get_partial'

  resources :users, only: [:show, :index, :destroy, :edit, :update] do
    patch :update_perms, on: :member
  end
  resources :blog, except: [:show]
  resources :clubs do
    post :apply, on: :member
    post :unapply, on: :member
  end

  resources :reports do
    post :respond, on: :member
  end
  resources :events
  resources :announcements
  resources :account_activations, only: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include Friendlyable

  has_many :announcements, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :blog_posts, dependent: :destroy
  has_many :leaderships, foreign_key: "president_id", class_name: "Club", dependent: :destroy
  has_many :club_members, dependent: :destroy
  has_many :clubs, through: :club_members
  has_many :mod_actions
  has_many :reports
  has_many :responses, foreign_key: "responder_id", class_name: "Report", dependent: :destroy

  has_and_belongs_to_many :roles
  has_and_belongs_to_many :events
  has_and_belongs_to_many :class_years
  


  attr_accessor :remember_token, :activation_token
  before_save :downcase_email
  default_scope -> {order(:created_at)}
#  before_create :create_activation_digest

  validates :name, presence: true,
                   length: {maximum: 50}

  validates :email, presence: true,
                    length: {maximum: 255},
                    format: { with: /\A[\w+\-.]+@punahou\.edu/i },
                    uniqueness: { case_sensitive: false }


  def self.get_color rank
    colors[rank]
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def find_classyear
    number_index = (email =~ /[0-9]{2}/)
    ClassYear.find(email.split("")[number_index..number_index+1].join.to_i + 2000)
  end

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

#  def send_activation_email
#    UserMailer.account_activation(self).deliver_now
#  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def forget
      update_attribute(:remember_digest, nil)
  end

  def redirect_stuff
    redirect_to root_url
  end

  def can_do permission
    self.roles.map {|r| r.send(permission)}.include?(true)
  end

  def smart_class_years
    if self.class_years.any?
      self.class_years 
    else
      ClassYear.all
    end
  end


  def smart_class_year_ids
    smart_class_years.map { |c| c.id.to_s }
  end

  private

    def save_classyears
      self.class_years = [find_classyear]
    end
  
    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.email = auth.info.email
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        if user.valid?
          user.save!
        end
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action -> { correct_user(:admin) }, only: [:edit, :update]
  before_action -> { has_permission(:admin) }, only: [:destroy, :update_perms]
  before_action -> { has_permission(:approve) }, only: [:index]
  before_action :not_logged_in, only: [:new, :create]

  def banned?
    return true if !@user.roles.find_by(role_id: 6).nil?
  end

  def show
    @user = User.find_by_hash_id(params[:id])
    unless @user
      flash[:warning] = "That user does not exist!"
      redirect_to root_url
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def edit
    @user = User.find_by_hash_id(params[:id])
  end

  def update
    @user = User.find_by_hash_id(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Settings updated"
      redirect_to @user
      if (@user.class_years.empty?)
        @user.class_years = ClassYear.all
      end
    else
      render 'edit'
    end
  end

  def destroy
    User.find_by_hash_id(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def update_perms
    @user = User.find_by_hash_id(params[:id])
    if (@user.roles.include?(Role.find(1)))
      @user.roles = [Role.find(1)]
    else
      @user.roles = []
    end

    params[:user][:roles].each do |r|
      @user.roles << Role.find(r) unless r.empty?
    end
    redirect_to @user
  end

  private

    def user_params
      params.require(:user).permit(:biography, class_year_ids: [])
    end

    def not_logged_in
      if logged_in?
        redirect_to(root_url)
        flash[:danger] = "You aren't allowed to do that!"
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_badges.html.erb
<% if logged_in? %>
  <% user.roles.each do |r| %>
    <span class="badge" style="color: white; background-color: #<%= r.color %>"><%= r.name %></span>
  <% end %>
<% end %>

<!--%= render 'users/badges', user: user %-->

app/views/users/_colored_name.html.erb
<% rank = "#{get_highest_rank_color user}" %>
<span style="color: #<%= rank %>"><%= user.name %> </span>

app/views/users/_colored_name_link.html.erb
<% if logged_in? %> <%= link_to (render "users/colored_name", user: user), user %> <% end %> 

app/views/users/_params.html.erb
<!-- parameters: "url", "submit_text" -->
<%= form_for(@user, url: url) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <label>See posts for these classes:</label>
    <%= f.collection_check_boxes(:class_year_ids, ClassYear.all, :id, :id) do |c| %>
      <div class="custom-control custom-checkbox">
        <%= c.check_box(class: "custom-control-input")%>
        <%= c.label(class: "custom-control-label") %>
      </div>
    <% end %>
  </div>
  <%= f.submit submit_text, class: "btn btn-primary" %>
<%end%>

app/views/users/_roleselect.html.erb
<%= form_for(@user, url: update_perms_user_path(@user.hash_id)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <label>Roles</label>
    <%= f.collection_check_boxes(:roles, Role.all[1..Role.count-1], :id, :name) do |c| %> 
      <div class="custom-control custom-checkbox">
        <%= c.check_box(class: "custom-control-input", checked: @user.roles.include?(c.object)) %>
        <%= c.label(class: "custom-control-label") %> 
      </div>
    <% end %>
  </div>

  <%= f.submit "Update", class: "btn btn-primary" %>
<%end%>

app/views/users/_user.html.erb
<tr>
  <td>
    <%= render "users/colored_name_link", user: user %>
  </td>
  <td class="text-secondary">
    <%= user.email %>
  </td>
  <td>
    <% if current_user.can_do(:admin) && !current_user?(user) %>
      <% if options %>

        <%= link_to "Edit", edit_user_path(user), class: "text-warning" %> |  
        <%= link_to "Delete", user_path(user), method: :delete, class: "text-danger",
                                   data: {confirm: "Are you sure you want to do this?"} %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/users/_user_table.html.erb
<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col" style="width: 300px">Name</th>
      <th scope="col">Email</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%= render users, options: options %>
  </tbody>
</table>

app/views/users/edit.html.erb
<% provide :title, "Account Settings" %>
<div class="card">
  <div class="card-header blue darken-3 white-text">
    <h4 class="card-title">
      Settings
  </div>
  <div class="card-body">
    <%= render "users/params", url: nil, submit_text: "Save Edits" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h2>User List</h2>

<%= will_paginate %>
<%= render 'users/user_table', users: @users, options: true %>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, "Sign Up" %>
<h2>Sign Up</h2>
<div class="alert alert-warning" role="alert">
  Unless you have talked to one of the administrators of the site, creating your account at this time will not do anything.
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'layouts/userparams', url: signup_url, submit_text: "Create Account" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h2 class="lato-title"><%= render 'users/colored_name', user: @user %></h2>
        <%= render 'users/badges', user: @user %>
        <div class="row">
          <div class="col-lg-11">
            <h3 style="margin-bottom: 0px;"><small class="text-muted"><%= @user.email %></small></h3>
          </div>
          <div class="col-lg-1 custom-flex-bottom custom-flex-right">
            <!--
              Here lies the grave of the edit user bio button...
              R.I.P 2018-2018
            -->
          </div>
        </div>
        <hr />
        <div class="row">
          <div class="col-md-8">
            <% unless @user.biography.blank? %>
              <div class="card card-body">
                <h4>Biography</h4>
                <hr style="margin-top: 0px">
                <%= markdown(@user.biography) %>
              </div>
            <% end %>
          </div>
        </div>
        <% if logged_in? && current_user.can_do(:admin) %>
          <%= render 'users/roleselect' %>
        <% end %>
      </div>
    </div>
  </div>
</div>