config/routes.rb
Rails.application.routes.draw do
  get 'blog/new'
  #get 'blog/create'
  get 'blog/edit'
  #get 'blog/update'
  get 'blog/destroy'
  root 'pages#home'
  get '/help', to: 'pages#help'
  get '/contact', to: 'pages#contact'
  get '/home', to: 'pages#home'
  get '/staff', to: 'pages#staff'
  get '/feedback', to: 'pages#feedback'
  get '/modlog', to: 'pages#modlog'
  get '/mystuff', to: 'pages#mystuff'
  get '/my%20stuff', to: 'pages#mystuff'

  get '/plc', to: 'plc#index'
  get '/plc/subject', to: 'plc#subject_slots'

  delete '/logout', to: 'sessions#destroy'
  get '/filter/get', to: 'filters#get', as: 'get_filter'
  post '/filter/update', to: 'filters#update', as: 'update_filter'
  #google
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  post '/event/approve', to: 'events#approve', as: 'approve_event'
  post '/event/reject', to: 'events#reject', as: 'reject_event'
  post '/event/finalize', to: 'events#finalize', as: 'finalize_event'
  get '/event/get_partial', to: 'events#get_partial', as: 'event_get_partial'
  post '/event/rsvp', to: 'events#rsvp', as: 'rsvp_event'
  post '/event/unrsvp', to: 'events#unrsvp', as: 'unrsvp_event'

  post '/announcement/approve', to: 'announcements#approve', as: 'approve_announcement'
  post '/announcement/reject', to: 'announcements#reject', as: 'reject_announcement'
  post '/announcement/finalize', to: 'announcements#finalize', as: 'finalize_announcement'
  get '/announcement/get_partial', to: 'announcements#get_partial', as: 'announcement_get_partial'

  post '/club/approve', to: 'clubs#approve', as: 'approve_club'
  post '/club/reject', to: 'clubs#reject', as: 'reject_club'
  post '/club/finalize', to: 'clubs#finalize', as: 'finalize_club'
  get '/club/get_partial', to: 'clubs#get_partial', as: 'club_get_partial'

  resources :users, only: [:show, :index, :destroy, :edit, :update] do
    patch :update_perms, on: :member
  end
  resources :blog, except: [:show]
  resources :clubs do
    post :apply, on: :member
    post :unapply, on: :member
  end

  resources :reports do
    post :respond, on: :member
  end
  resources :events
  resources :announcements
  resources :account_activations, only: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  include Friendlyable
  include Filterable
  include ApprovableModel

  belongs_to :user, dependent: :destroy
  belongs_to :club, optional: true
  default_scope -> { order('start_time ASC') }
  validates :title, presence: true, length: {maximum: 50}
  validates :user_id, presence: true
  validates :location, presence: true, length: {maximum: 140}
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :ends_after_start
  validate :date_in_future
  has_and_belongs_to_many :users

  scope :finalized, -> { where(final: true) }
  scope :today, -> { where(start_time: DateTime.now.getlocal('-10:00').beginning_of_day..DateTime.now.getlocal('-10:00').end_of_day) }
  scope :tomorrow, -> { where(start_time: (DateTime.now.getlocal('-10:00').beginning_of_day + 1.day)..(DateTime.now.getlocal('-10:00').end_of_day + 1.day)) }
  scope :day_after_tomorrow, -> { where(start_time: (DateTime.now.getlocal('-10:00').beginning_of_day + 2.days)..(DateTime.now.getlocal('-10:00').end_of_day + 2.days)) }
  scope :future_events, -> { where("start_time > ?", DateTime.now.getlocal('-10:00')) }
  scope :past_events, -> { where("start_time < ?", DateTime.now.getlocal('-10:00')) }
  scope :future_day_events, -> { where("start_time > ?", DateTime.now.getlocal('-10:00').beginning_of_day) }
  scope :set_day_events, -> (day) { where(start_time: day.beginning_of_day..day.end_of_day)}
  scope :by_user, -> (user) {
    joins(:users).where(users: {id: user})
  }

  def ends_after_start
    if (end_time < start_time)
      errors.add(:end_time, 'must be after the start time')
    end
  end

  def next user
    Event
        .where("start_time < ?", start_time)
        .where(approved: true)
        .future_events
        .last
  end

  def prev user
    Event
        .where("start_time > ?", start_time)
        .where(approved: true)
        .future_events
        .first
  end

  def past?
    start_time < Time.zone.now
  end

  def date_in_future
    if (start_time < Time.zone.now)
      errors.add(:start_time, "must be in the future #{start_time}, #{Time.zone.now}")
    end

    if (end_time < Time.zone.now)
      errors.add(:end_time, 'must be in the future')
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  include Approvable

  def linked_model
    Event
  end

  before_action -> {has_permission :admin}, only: [:destroy]

  before_action :not_banned, only: [:new, :create, :update, :edit]
  before_action :logged_in_user


  def show
    @event = Event.friendly.find(params[:id])
  end

  def index
    if logged_in?
      if (current_user.can_do(:approve) || current_user.can_do(:faculty_mod))
        @events = Event.future_events
        @filter = params[:filter]
        if params[:filter] == 'Rejected'
          @events = @events.rejected
        elsif params[:filter] == 'Approved'
          @events = @events.approved
        elsif params[:filter] == 'Pending'
          @events = @events.awaiting_approval
        elsif params[:filter] == 'Past'
          @events = Event.past_events
        end
      else
        @events = Event.future_events.approved
      end
    else
      @events = Event.future_events.approved
    end
  end

  def destroy
    Event.friendly.find(params[:id]).delete
    flash[:success] = "Event deleted!"
    redirect_to events_url
  end

  def edit
    @event = Event.friendly.find(params[:id])
  end

  def update
    @event = Event.friendly.find(params[:id])
    if (@event.update_attributes(event_params))
      flash.now[:success] = "Event updated"
      redirect_to event_path(@event)
      current_user.mod_actions.create(description: "Edited Event " + @event.hash_id,
      link: 'events/' + @event.hash_id)
    else
      render 'edit'
    end
  end

  def new
    @event = current_user.events.build
  end



  def rsvp
    @event = Event.friendly.find(params[:id])
    unless @event.users.exists?(current_user.id)
      @event.users << current_user
    end
    if (params[:redirect])
      redirect_to request.referrer
    end
  end

  def unrsvp
    @event = Event.friendly.find(params[:id])
    if @event.users.exists?(current_user.id)
      @event.users.destroy(current_user)
    end
    if (params[:redirect])
      redirect_to request.referrer
    end
  end

  def create
    @event = current_user.events.build(event_params)
    @event.user_id = current_user.id
    @event.approved = !!(current_user.can_do(:approve))
    if (@event.save)
      if (@event.approved)
        flash[:success] = "Event created!"
        redirect_to @event
      else
        flash[:danger] = "Your event is anxiously awaiting moderator approval."
        redirect_to events_path
      end
    else
      render 'new'
    end
  end



  #private

  def event_params
    new_params = params.require(:event).permit(:title, :location, :description, :approved, :club)

    unless params[:start].nil?
      new_params[:start_time] = DateTime.strptime(params[:start], '%b-%d-%y %H:%M') + 10.hours
    end
    unless  params[:end].nil?
      new_params[:end_time] = DateTime.strptime(params[:end], '%b-%d-%y %H:%M') + 10.hours
    end
    unless new_params[:club].nil?
      unless new_params[:club].empty?
        new_params[:club] = Club.find(new_params[:club])
      else
        new_params[:club] = nil
      end
    end

    new_params
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<% color = "" %>
<% if logged_in? %>


<% rsvp = event.users.exists?(current_user.id) %>
<% id = event.id %>
  <%= content_tag :li, class: "list-group-item " + get_background_color_for_partial(event), id: event.hash_id do %>
    <div class="row">
      <div class="col-md-2 custom-flex-center">
        <span>
          <%= event.start_time.strftime("%b")%>
          <%= event.start_time.strftime("%d")%>,
          <%= event.start_time.strftime("%l:%M %p")%>
        </span>
      </div>
      <% if current_user.can_do(:approve) %>
        <div class="col-md-5 custom-flex-center">
      <% else %>
        <div class="col-md-7 custom-flex-center">
      <% end %>
        <%= content_tag :h6, class: 'no-margin', style: 'width: 100%' do %>
          <%= link_to event.title, event, class: 'font-italic' if event.past? %>
        <% end %>

        <small style="width: 100%;">
          Posted by
          <%= render 'users/colored_name_link', user: User.find(event.user_id) %>
          <%= distance_of_time_in_words(event.created_at.to_time, Time.now) + " ago" %>
        </small>
      </div>

      <% if current_user.can_do(:approve) %>
        <div class="col-md-5 custom-flex-center custom-flex-right">
      <% else %>
        <div class="col-md-3 custom-flex-center custom-flex-right">
      <% end %>
      <% if event.approved && event.final %>
        <% unless rsvp %>
          <%= content_tag :a, "Not Attending", class: "btn btn-sm btn-outline-blue-grey float-right rsvp",
          onclick: "rsvp(\"#{event.hash_id}\", true)" %>
        <% else %>
          <%= content_tag :a, "Attending", class: "btn btn-sm btn-outline-success float-right rsvp",
          onclick: "rsvp(\"#{event.hash_id}\", false)" %>
        <% end %>
      <% end %>
      
      <div class="options">
        <%= render 'shared/admin_buttons', model_name: 'event', object: event,
                                           edit_url: edit_event_path(event),
                                           destroy_url: event_path(event) %>
      </div>
      
    </div>
  </div>
<% end %>
<% elsif !logged_in? %>
  <% flash.now[:danger] = "Log in to view events!" %>
<% end %>

app/views/events/_eventsparams.html.erb
<%= form_for(@event, url: url) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time, :order => [:month, :day, :year, :hour, :minute] %>
  </div>

  <div class="form-group">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time, :order => [:month, :day, :year, :hour, :minute] %>
  </div>

  <% unless url.nil? %>
    <% if current_user.leaderships.any? %>
      <div class="form-group">
        <label style="margin-bottom: 0px">Club</label>
        <%= f.collection_radio_buttons(:club, clubs, :id, :name) do |club| %>
          <div class="custom-control custom-radio">
            <%= club.radio_button(class: "custom-control-input") %>
            <%= club.label(class: "custom-control-label") %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <% if submit_text == "Post" || submit_text == "Send to purgatory"%>
    <%= f.submit submit_text, class: "btn blue darken-3" %>
  <% elsif submit_text == "Save Edits"%>
    <%= f.submit submit_text, class: "btn btn-outline-warning" %>
  <% end %>
<% end %>

app/views/events/_homepage.html.erb
<div class="card">
  <div class="card-header blue darken-3 white-text">
    <h4 class="card-title">
      <%= content_tag(:a, "Upcoming Events", href: events_path, class: "text-white")%>
      <i class="fas fa-calendar float-right"></i>
    </h4>
  </div>
  <div class="card-body m-0" style="padding: 0px;">
    <% if !!@first_nonempty_day %>
      <div class="card-group">
        <div class="card border-left-0 border-top-0 border-bottom-0">
          <div class="card-header white">
            <h5 class="card-title m-0 event-card-title">
              <%= @first_nonempty_day.to_date === Date.today ? "Today" :
              (@first_nonempty_day.to_date === Date.tomorrow ? "Tomorrow" :
              @first_nonempty_day.strftime("%A, %m/%d")) %>
            </h5>
          </div>
          <ul class="list-group list-group-flush">
            <% @first_day_events.each do |event| %>
              <li class="list-group-item">
                <%= event.start_time.strftime('%I:%M %p') %> - <%= link_to event.title, event_path(event) %>
              </li>
            <% end %>
          </ul>
        </div>
        <% unless @second_nonempty_day.nil? %>
          <div class="card border-0">
            <div class="card-header white">
              <h5 class="card-title m-0 event-card-title">
                <%= @second_nonempty_day.to_date === Date.tomorrow ? "Tomorrow" :
                @second_nonempty_day.strftime("%A, %m/%d") %>
              </h5>
            </div>
            <ul class="list-group list-group-flush">
              <% @second_day_events.each do |event| %>
                <li class="list-group-item">
                  <%= event.start_time.strftime('%I:%M %p') %> - <%= link_to event.title, event_path(event) %>
                </li>

              <% end %>
            </ul>
          </div>
        <% else %>
          <div class="card border-0">
            <div class="card-header white">
              <h5 class="card-title event-card-title">
                No More Events
              </h5>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><%= link_to "Create your own?", new_event_path %></li>
            </ul>
          </div>
        <% end %>
      </div>
      <div class="card-footer white">
        <%= link_to "See more...", events_path %>
      </div> 
    <% else %>
      <div class="card-body">
        <h5 class="card-title">Nothing Here Yet...</h5>
        <%= link_to "Create your own event?", new_event_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<% provide(:title, "Editing Event") %>
<div class="row">
  <div class="col-lg-9">
    <div class="card">
      <div class="card-header warning-color-dark white-text">
        <h4 class="card-title" style="text-align: center;">
          Edit Event
        </h4>
      </div>
      <div class="card-body">
        <h2><%= @event.title %></h2>
        <%= render 'layouts/eventsparams', url: nil, submit_text: "Save Edits" %>
      </div>
    </div>
  </div>
  <div class="col-md-3" style="padding-left: 0px">
    <%= render 'shared/rules.html.erb' %>
  </div>
</div>

app/views/events/index.html.erb
<% provide(:title, "Events") %>
<% if logged_in? %>
  <div class="card">
    <div class="card-header blue darken-3 white-text">
      <div class="float-left">
        <div class="float-left">
          <%= render 'shared/index_dropdown', name: "Events", 
          filter_options: %w{Approved Pending Rejected Past} + ["My Class"] %>
        </div>
      </div>
      <div class="float-right">
        <% if logged_in? %>
          <%= link_to ("New Event").html_safe, new_event_path,
            class: "btn btn-sm btn-white black-text"%>
        <% end %>
      </div>
    </div>
    <div class="card-body" style="padding: 0px;">
      <ul class="list-group list-group-flush">
        <%= render @events %>
      </ul>
    </div>
  </div>
<% else %>
  <% flash.now[:warning] = "Log in to view events" %>
<% end %>

app/views/events/new.html.erb
<% provide(:title, "New Event") %>
<div class="row">
  <div class="col-lg-9">
    <div class="card">
      <div class="card-header success-color white-text">
        <h4 class="card-title" style="text-align: center;">
          New Event
        </h4>
      </div>
      <div class="card-body">
        <% if current_user.can_do :moderate %>
          <%= render 'layouts/eventsparams', url: events_url, submit_text: "Post",
          clubs: current_user.leaderships %>
        <% else %>
          <%= render 'layouts/eventsparams', url: events_url, submit_text: "Submit for Approval",
          clubs: current_user.leaderships %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-3" style="padding-left: 0px">
    <%= render 'shared/rules.html.erb' %>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <%= content_tag :div, class: "card-body " + get_background_color_for_partial(@event) do %>
        <div>
          <!--
          <div class="row navigation-tools">
            <div class="col-lg-12">
              <div class="float-left">
                <%= link_to "Back", :back, class: "btn btn-sm btn-outline-blue-grey darken-3 navigation-tools-back" %>
              </div>
              <%= render "shared/scroll", object: @event %>
            </div>
          </div>
          -->
          <h2 class="lato-title"><%= @event.title %></h2>
          <small>
            Created by
          <%= render 'users/colored_name_link', user: User.find(@event.user_id) %>
          </small>
          <%= render 'users/badges', user: User.find(@event.user_id) %>
          <small>
            <%= distance_of_time_in_words(@event.created_at.to_time, Time.now) %>
            ago<% if @event.updated_at != @event.created_at %>,
            Last updated <%= distance_of_time_in_words(@event.updated_at.to_time, Time.now) %> ago
            <% end %>

          </small>

          <div class="options float-right">
            <%= render 'reports/new_report_popover' %>
            <%= render 'shared/admin_buttons', model_name: 'event', object: @event,
                                               edit_url: edit_event_path(@event),
                                               destroy_url: event_path(@event) %>
          </div>
        </div>
        <hr />
        <div>
          <b>Location:</b> <%= @event.location %>
          <br>
          <br>
          <% unless @event.start_time.to_date == @event.end_time.to_date %>
            <%=  @event.start_time.strftime("%A %B %d, %I:%M %p") %> — <%=  @event.end_time.strftime("%A %B %d, %I:%M %p") %><br>
          <% else %>
            <%= @event.start_time.strftime("%A %B %d, %I:%M %p") %> - <%= @event.end_time.strftime("%I:%M %p")%><br>
          <% end %>

          <br>
          <%= markdown @event.description %>

          <% unless @event.club.nil? %>
            Sponsored by <%= link_to @event.club.name, @event.club %>
          <% end %>
          <br><br>

        </div>

          <% if logged_in? %>
            <div class="btn-group">
              <% unless @event.users.exists?(current_user.id) %>
                <%= link_to "Not Attending", rsvp_event_path(id: @event.id, redirect: true), method: :post, class: "btn btn-sm btn-outline-blue-grey float-right" %>
              <% else %>
                <%= link_to "Attending", unrsvp_event_path(id: @event.id, redirect: true), method: :post, class: "btn btn-sm btn-outline-success float-right" %>
              <% end %>
            </div>
          <% end %>
          <% if (@event.user_id == current_user.id || current_user.can_do(:approve)) && !@event.users.empty? %>
            <h6><br>Current attendees: <%= @event.users.all.count %></h6>
            <ul>
              <% @event.users.each do |attendee| %>
                <li><%= attendee.email %></li>
              <% end %>
            </ul>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  $(".model-action").on('click', function() {
    console.log('click')
    setTimeout(function() {
      location.reload(true) 
    }, 200)
  })
</script>