config/routes.rb
Rails.application.routes.draw do
  get 'blog/new'
  #get 'blog/create'
  get 'blog/edit'
  #get 'blog/update'
  get 'blog/destroy'
  root 'pages#home'
  get '/help', to: 'pages#help'
  get '/contact', to: 'pages#contact'
  get '/home', to: 'pages#home'
  get '/staff', to: 'pages#staff'
  get '/feedback', to: 'pages#feedback'
  get '/modlog', to: 'pages#modlog'
  get '/mystuff', to: 'pages#mystuff'
  get '/my%20stuff', to: 'pages#mystuff'

  get '/plc', to: 'plc#index'
  get '/plc/subject', to: 'plc#subject_slots'

  delete '/logout', to: 'sessions#destroy'
  get '/filter/get', to: 'filters#get', as: 'get_filter'
  post '/filter/update', to: 'filters#update', as: 'update_filter'
  #google
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  post '/event/approve', to: 'events#approve', as: 'approve_event'
  post '/event/reject', to: 'events#reject', as: 'reject_event'
  post '/event/finalize', to: 'events#finalize', as: 'finalize_event'
  get '/event/get_partial', to: 'events#get_partial', as: 'event_get_partial'
  post '/event/rsvp', to: 'events#rsvp', as: 'rsvp_event'
  post '/event/unrsvp', to: 'events#unrsvp', as: 'unrsvp_event'

  post '/announcement/approve', to: 'announcements#approve', as: 'approve_announcement'
  post '/announcement/reject', to: 'announcements#reject', as: 'reject_announcement'
  post '/announcement/finalize', to: 'announcements#finalize', as: 'finalize_announcement'
  get '/announcement/get_partial', to: 'announcements#get_partial', as: 'announcement_get_partial'

  post '/club/approve', to: 'clubs#approve', as: 'approve_club'
  post '/club/reject', to: 'clubs#reject', as: 'reject_club'
  post '/club/finalize', to: 'clubs#finalize', as: 'finalize_club'
  get '/club/get_partial', to: 'clubs#get_partial', as: 'club_get_partial'

  resources :users, only: [:show, :index, :destroy, :edit, :update] do
    patch :update_perms, on: :member
  end
  resources :blog, except: [:show]
  resources :clubs do
    post :apply, on: :member
    post :unapply, on: :member
  end

  resources :reports do
    post :respond, on: :member
  end
  resources :events
  resources :announcements
  resources :account_activations, only: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  before_action -> {has_permission(:admin)}, except: [:index, :show]

  def new
    @blogpost = current_user.blog_posts.build if current_user.can_do(:admin)
  end

  def create
    @blogpost = current_user.blog_posts.build(blogpost_params)
    if (@blogpost.save) 
      flash[:success] = "Blog post created!"
      redirect_to blog_index_url 
    else
      render 'new'
    end
  end

  def index
    @blogposts = BlogPost.all
  end

  def edit
    @blogpost = BlogPost.find_by_hash_id(params[:id])
  end

  def update
    @blogpost = BlogPost.friendly.find(params[:id])
    if (@blogpost.update_attributes(blogpost_params))
      flash[:success] = "Blogpost updated"
      redirect_to blog_index_url + '#' + @blogpost.hash_id
    else
      render 'edit'
    end
  end

  def destroy
    BlogPost.find_by_hash_id(params[:id]).delete
    flash[:success] = "Blog post deleted!"
    redirect_to blog_index_url
  end


  private
    def blogpost_params
      params.require(:blog_post).permit(:content, :title)
    end

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_blog_post.html.erb
<%= content_tag(:div, class: "card card-body", id: blog_post.hash_id) do %>
  <div>
    <div class="float-left">
      <h3 class="card-title"><%= blog_post.title %></h2>

      <div class="float-left">
        <small>
        Created by
          <%= render 'users/colored_name_link', user: User.find(blog_post.user_id) %>
        </small>
        <%= render 'users/badges', user: User.find(blog_post.user_id) %>
        <small>
          <%= distance_of_time_in_words(blog_post.created_at.to_time, Time.now) %> ago<% if blog_post.updated_at != blog_post.created_at %>,
            Last updated <%= distance_of_time_in_words(blog_post.updated_at.to_time, Time.now) %> ago 
          <% end %>
        </small>
        
      </div>
    </div>


    <% if logged_in? %>
      <% if current_user.can_do :moderate %>
        <div class="float-right">
          <%= link_to "Edit", edit_blog_path(blog_post), class: "text-warning"%> |
          <%= link_to "Delete", blog_path(blog_post), method: :delete, class: "text-danger", 
                    data: {confirm: "Are you sure you want to do this?"} %>
        </div>
      <% end %>
    <% end %>
    <br>
  </div>
  <hr style="margin: 10px">
  <div>
      <%= markdown(blog_post.content).html_safe %>
  </div>

<% end %>

app/views/blog/_blogparams.html.erb
<%= form_for(@blogpost, url: url) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <%= f.submit submit_text, class: "btn btn-primary" %>
<% end %>

app/views/blog/edit.html.erb
<% provide(:title, "Editing Blog Post") %>
<h2>Editing Post: <%= @blogpost.title %></h2>
<%= render 'blog/blogparams', url: blog_path, submit_text: "Save Edits" %>

app/views/blog/index.html.erb
<% provide(:title, "Blog") %>

<div class="row">
  <div class="col-md-9">
    <div class="card card-body">
      <h2 class="card-title">
        <div class="float-left">
          Student Hub Blog
          <small class="text-muted">All the freshest news</small>
        </div>
        <% if logged_in? && current_user.can_do(:admin)%>
          <%= link_to "New Post", new_blog_path, class: "float-right btn btn-sm btn-outline-primary blog-header-button"%>
        <% end %>
      </h2>
    </div>
    <%= render @blogposts %>
  </div>
  <div class="col-md-3 order-first order-md-2">
    <div class="card card-body">
      <h5 class="card-title">Quick Jump</h5>
      <ul style="padding: 5px 0px 0px 20px">
        <% @blogposts.each do |b| %>
          <%= content_tag(:li, content_tag(:a, b.title, href: "##{b.hash_id}")) %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/blog/new.html.erb
<% provide(:title, "New Blog Post") %>
<h2>New Blog Post</h2>
<%= render 'blog/blogparams', url: blog_index_url, submit_text: "Post" %>

app/views/blog/show.html.erb
<% provide(:title, @blogpost.title) %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="float-left">
        <h2><%= @blogpost.title %></h2>

        
        <div class="float-left">
          <small>
          Created by
            <%= render 'users/colored_name_link', user: User.find(@blogpost.user_id) %>
          </small>
          <%= render 'users/badges', user: User.find(@blogpost.user_id) %>
          <small>
            <%= distance_of_time_in_words(@blogpost.created_at.to_time, Time.now) %> ago<% if @blogpost.updated_at != @blogpost.created_at %>, Last updated <%= distance_of_time_in_words(@blogpost.updated_at.to_time, Time.now) %> ago 
            <% end %>
          </small>
        </div>
      </div>

      <% if logged_in? %>
        <% if current_user.can_do :admin %>
          <div class="float-right">
            <%= link_to "Edit", edit_blog_path(@blogpost), class: "text-warning"%> |
            <%= link_to "Delete", blog_path(@blogpost), method: :delete, class: "text-danger", 
                      data: {confirm: "Are you sure you want to do this?"} %>
          </div>
        <% end %>
      <% end %>
        
    </div>
  </div>
  <br>
  <div class="row justify-content-center">
    <div class="col-md-9"><%= simple_format @blogpost.content %></div>
  </div>
</div>

app/views/blog/update.html.erb
<h1>Blog#update</h1>
<p>Find me in app/views/blog/update.html.erb</p>