config/routes.rb
Rails.application.routes.draw do
  get 'blog/new'
  #get 'blog/create'
  get 'blog/edit'
  #get 'blog/update'
  get 'blog/destroy'
  root 'pages#home'
  get '/help', to: 'pages#help'
  get '/contact', to: 'pages#contact'
  get '/home', to: 'pages#home'
  get '/staff', to: 'pages#staff'
  get '/feedback', to: 'pages#feedback'
  get '/modlog', to: 'pages#modlog'
  get '/mystuff', to: 'pages#mystuff'
  get '/my%20stuff', to: 'pages#mystuff'

  get '/plc', to: 'plc#index'
  get '/plc/subject', to: 'plc#subject_slots'

  delete '/logout', to: 'sessions#destroy'
  get '/filter/get', to: 'filters#get', as: 'get_filter'
  post '/filter/update', to: 'filters#update', as: 'update_filter'
  #google
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  post '/event/approve', to: 'events#approve', as: 'approve_event'
  post '/event/reject', to: 'events#reject', as: 'reject_event'
  post '/event/finalize', to: 'events#finalize', as: 'finalize_event'
  get '/event/get_partial', to: 'events#get_partial', as: 'event_get_partial'
  post '/event/rsvp', to: 'events#rsvp', as: 'rsvp_event'
  post '/event/unrsvp', to: 'events#unrsvp', as: 'unrsvp_event'

  post '/announcement/approve', to: 'announcements#approve', as: 'approve_announcement'
  post '/announcement/reject', to: 'announcements#reject', as: 'reject_announcement'
  post '/announcement/finalize', to: 'announcements#finalize', as: 'finalize_announcement'
  get '/announcement/get_partial', to: 'announcements#get_partial', as: 'announcement_get_partial'

  post '/club/approve', to: 'clubs#approve', as: 'approve_club'
  post '/club/reject', to: 'clubs#reject', as: 'reject_club'
  post '/club/finalize', to: 'clubs#finalize', as: 'finalize_club'
  get '/club/get_partial', to: 'clubs#get_partial', as: 'club_get_partial'

  resources :users, only: [:show, :index, :destroy, :edit, :update] do
    patch :update_perms, on: :member
  end
  resources :blog, except: [:show]
  resources :clubs do
    post :apply, on: :member
    post :unapply, on: :member
  end

  resources :reports do
    post :respond, on: :member
  end
  resources :events
  resources :announcements
  resources :account_activations, only: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :responder, class_name: "User", foreign_key: "responder_id", optional: true

  scope :completed, -> {where(response: nil)}
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :not_banned, only: [:create, :new, :show]
  before_action -> { correct_user(:moderate) }, only: [:show]
  before_action -> { has_permission(:moderate)}, only: [:index, :respond]

  def index
    if (params[:see_responded])
      @reports = Report.all.paginate(page: params[:page], per_page: 30)
    else
      @reports= Report.completed.paginate(page: params[:page], per_page: 30)
    end
  end

  def new
    @report = current_user.reports.build
  end

  def create
    @report = current_user.reports.build(report_params)
    @report.link = params[:link]
    if (@report.save)
      flash[:info] = "Report created. A staff member will respond shortly."
      redirect_to report_path(@report)
    end

  end

  def show
    @report = Report.find(params[:id])
  end

  def respond
    @report = Report.find(params[:id])
    @report.update_attributes(response: params[:response][:response], responder: User.find(params[:user]))
    redirect_to request.referrer
  end

  private

  def report_params
    params.require(:report).permit(:report, :link, :user_id)
  end


end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_new_report_popover.html.erb
<% if logged_in? %>
<div style="margin-right: 5px;">
  <button type="button" class="btn btn-sm btn-danger" data-toggle="popover" id="report-popover"
          style="padding: 5px 10px 5px 10px; " data-placement="bottom" trigger="focus">Report
  </button>
</div>
<div id="popover-head" style="display: none">
  Report This Post
</div>
<div id="popover-content" style="display: none">
  <%= form_for :report, url: reports_path, html: {id: 'report-form'} do |f| %>
    <input name="link" type="hidden" id="location" >
    <div class="form-group" style="margin-bottom: 5px">
      <%= f.label :report, "What is wrong with this post?" %>
      <%= f.text_area :report, class: "form-control", style: "font-size: 9pt" %>
    </div>

    <%= f.submit "Submit", class: "btn btn-sm btn-primary float-right", style: "padding: 5px 10px 5px 10px; margin-bottom: 5px" %>
    <br>

  <% end %>
</div>
<script>
/*
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
*/
$('#report-popover').popover({
    html : true,
    title: function() {
      return $("#popover-head").html();
    },
    content: function() {
      return $("#popover-content").html();
    }
});
$('#location').attr('value', window.location.href)

var popover_on = false;
document.onmouseup = function(e) {
  var button_rect = document.getElementById("report-popover").getBoundingClientRect()
  var mouseX = e.clientX;
  var mouseY = e.clientY;
  if(mouseY > button_rect.top && mouseY < button_rect.bottom && mouseX > button_rect.left && mouseX < button_rect.right) {
    $('[data-toggle="popover"]').popover('show');
    popover_on = true;
  } else if(popover_on) {
    var popover_rect = document.getElementsByClassName("popover")[0].getBoundingClientRect();
    if(mouseY > popover_rect.top && mouseY < popover_rect.bottom && mouseX > popover_rect.left && mouseX < popover_rect.right) {

    } else {
      $('[data-toggle="popover"]').popover('hide');
      popover_on = false;
    }
  }
  /*
  if(mouseY > popover_rect.top && mouseY < popover_rect.bottom && mouseX > popover_rect.left && mouseX < popover_rect.right) {

  } else if(mouseY > button_rect.top && mouseY < button_rect.bottom && mouseX > button_rect.left && mouseX < button_rect.right) {
    $('[data-toggle="popover"]').popover('show');
  } else {
    $('[data-toggle="popover"]').popover('hide');
  }
  */
}
</script>
<% end %>

app/views/reports/_report.html.erb
<% if report.response.nil? %>
  <% color = 'red lighten-5' %>
<% else %>
  <% color = 'green lighten-5' %>
<% end %>

<%= content_tag :li,  class: "list-group-item ", style: "height: 50px" do %>
  <%= content_tag :tr, class: color do %>
    <%= content_tag :td, report.id %>
    <%= content_tag :td do %>
      <%= render 'users/colored_name', user: report.user %>
    <% end %>

    <%= content_tag :td do %>
      <% unless report.report.empty? %>
        <%= link_to report.report.split("")[0..100].join, report, style: "color: #007bff" %>
      <% else %>
        <%= link_to "No description provided", report, style: "color: #007bff" %>
      <% end %>
    <% end %>
    <%= content_tag :td, report.created_at.in_time_zone("Hawaii").strftime('%b %e, %l:%M %p') %>
  <% end %>
<% end %>

app/views/reports/index.html.erb
<h2>Reports</h2>
<%= form_tag(reports_path, method: 'GET', id: "form", enforce_utf8: false) do %>
  <div class="form-group">
    <% checked = !params[:see_responded].nil? %>
    <%= check_box_tag :see_responded, true, checked %>
    <%= label_tag "See Completed Reports" %>
  </div>
<% end %>
<%= will_paginate @reports %>
<table class="table-sm table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">User</th>
      <th scope="col">Report</th>
      <th scope="col">Time</th>
    </tr>
  </thead>
  <tbody>
    <%= render @reports %>
  </tbody>
</table>

<%= will_paginate @reports %>

<script>
  $('#see_responded').on('click', function() {
    $('#form').submit()
  })
</script>

app/views/reports/show.html.erb
<div class="card card-body">
  <div>
    <h2 class="card-title">
      <%= link_to "Report", @report.link %> #<%= @report.id %>
    </h2>
    <div class="mr-auto">
      <b>Submitted by <%= render 'users/colored_name_link', user: @report.user %></b>
    </div>
    
  </div>
  
  <hr>
  <%= @report.report %>

  <hr>

  <% if current_user.can_do(:moderate) && @report.response.nil? %> 
    <%= form_for :response, url: respond_report_path do |f| %>
      <input name="user" type="hidden" id="user-id" >
      <div class="form-group">
        <%= f.text_area :response, class: 'form-control' %>
      </div>
      
      <%= f.submit "Respond", class: 'btn btn-sm btn-primary float-right' %>

    <% end %>
  <% elsif !@report.response.nil? %>
    <b>Reponse from <%= render 'users/colored_name_link', user: @report.responder %>: </b>
    <p><%= @report.response %></p>
  <% end %>

  <% if current_user.can_do(:moderate ) %>
    <%= link_to "All Reports", reports_path %>
  <% end %>
</div>

<script>
$('#user-id').attr('value', <%= current_user.id %>)
</script>